name: 'AppEventAction'
description: 'Deploy eventbridge for microservice'
inputs:
  app-name:
    description: 'Application id'
    default: ''
  app-suffix:
    description: 'Suffix for namming'
    default: ''
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  terraform-version:
    description: 'Terraform version to install'
    default: '1.5.7'
  terragrunt-version:
    description: 'Terragrunt version to install'
    default: '0.68.1'
  application-repo:
    description: 'terraform-event-bus repository'
    default: 'FinalCAD/terraform-event-bus'
  application-ref:
    descrition: 'Ref to use for pulling repo terraform-event-bus'
    default: 'master'
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    default: ''
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    default: ''
  region-friendly:
    description: 'Finalcad region: frankfurt or tokyo'
    default: 'frankfurt'
  dry-run:
    description: 'Dry run'
    default: false
runs:
  using: 'composite'
  steps:
    - name: Deprecation of FinalCAD/AppEventAction
      shell: bash
      run: |
        echo '::error title=Deprecation of FinalCAD/AppEventAction::FinalCAD/AppEventAction has been deprecated. Use https://github.com/FinalCAD/AppMicroserviceAction instead.'
        exit 1
